<?php

return [
    'all' => [
        ['id' => 1 ,  'action' => 'view',           'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can view a specific task'],
        ['id' => 2 ,  'action' => 'create',         'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can create a task'],
        ['id' => 3 ,  'action' => 'update',         'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can update a task'],
        ['id' => 4 ,  'action' => 'changeStatus',   'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can change a task status'],
        ['id' => 5 ,  'action' => 'dispatch',       'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can dispatch a task'],
        ['id' => 6 ,  'action' => 'reassign',       'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can reassign a task to another agent'],
        ['id' => 7 ,  'action' => 'refine',         'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can refine a task location'],
        ['id' => 8 ,  'action' => 'cancel',         'module' => 'task' ,                     'label' => 'tasks',        'description' => 'User can cancel an undispatched task'],
        ['id' => 9 ,  'action' => 'view',           'module' => 'customer' ,                 'label' => 'customers',    'description' => 'User can view a specific customer'],
        ['id' => 10 , 'action' => 'create',         'module' => 'customer' ,                 'label' => 'customers',    'description' => 'User can create a customer'],
        ['id' => 11 , 'action' => 'update',         'module' => 'customer' ,                 'label' => 'customers',    'description' => 'User can update a customer'],
        ['id' => 12 , 'action' => 'view',           'module' => 'dashboard',                 'label' => 'dashboard',    'description' => 'User can view the dashboard'],
        ['id' => 13 , 'action' => 'view',           'module' => 'tracking',                  'label' => 'tracking',     'description' => 'User can track agents'],
        ['id' => 14 , 'action' => 'view',           'module' => 'planning',                  'label' => 'planning',     'description' => 'User can view planned tasks'],
        ['id' => 15 , 'action' => 'view',           'module' => 'inventory',                 'label' => 'inventory',    'description' => 'User can view the inventory'],
        ['id' => 16 , 'action' => 'create',         'module' => 'inventory',                 'label' => 'inventory',    'description' => 'User can add an item to the inventory'],
        ['id' => 17 , 'action' => 'edit',           'module' => 'inventory',                 'label' => 'inventory',    'description' => 'User can edit an item in the inventory'],
        ['id' => 18 , 'action' => 'view',           'module' => 'attendance',                'label' => 'attendance',   'description' => 'User can view agents attendances'],
        ['id' => 19 , 'action' => 'update',         'module' => 'attendance',                'label' => 'attendance',   'description' => 'User can check in/check out agents'],
        ['id' => 20 , 'action' => 'view',           'module' => 'order',                     'label' => 'orders',       'description' => 'User can view an order'],
        ['id' => 21 , 'action' => 'create',         'module' => 'order',                     'label' => 'orders',       'description' => 'User can create an order'],
        ['id' => 22 , 'action' => 'update',         'module' => 'order',                     'label' => 'orders',       'description' => 'User can update an order'],
        ['id' => 23 , 'action' => 'cancel',         'module' => 'order',                     'label' => 'orders',       'description' => 'User can cancel an order'],
        ['id' => 24 , 'action' => 'dispatch',       'module' => 'order',                     'label' => 'orders',       'description' => 'User can dispatch an order'],
        ['id' => 25 , 'action' => 'view',           'module' => 'accounting',                'label' => 'accounting',   'description' => 'User can dispatch an order'],
        ['id' => 26 , 'action' => 'reopen',         'module' => 'order',                     'label' => 'orders',       'description' => 'User can reopen an order'],
        ['id' => 27 , 'action' => 'view',           'module' => 'merchant',                  'label' => 'merchants',    'description' => 'User can view a merchant'],
        ['id' => 28 , 'action' => 'view',           'module' => 'agent',                     'label' => 'agents',       'description' => 'User can view an agent'],
        ['id' => 29 , 'action' => 'waybill',        'module' => 'order',                     'label' => 'orders',       'description' => 'User can print waybill'],
        ['id' => 30 , 'action' => 'revertToNew',    'module' => 'order',                     'label' => 'orders',       'description' => 'User can change orders from live to new'],
//        ['id' => 31 , 'action' => 'view',           'module' => 'management',              'label' => 'management',   'description' => 'User has access to management'],
        ['id' => 32 , 'action' => 'view',           'module' => 'reports',                   'label' => 'reports',      'description' => 'User has access to reports'],
    ],
];

